### ISSUE TITLE
Impossible de lancer l'application sur la version 1

### ISSUE THREAD

**Issue by ericsiber** [abdel-djalil/FizzKata#1]
La documentation ne précise pas comment lancer l'application correspondant à la version 1.

**Comment by abdel-djalil** [comment]
J'ai rajouté un exemple de l’utilisation de lib dans le readme, pour le lancement de la version 1 j'ai suivi le scénario de lancement de l'application ( s'il y'a {rule} V3 est lancée sinon V2 )

**Comment by ericsiber** [comment]
OK pour l'intégration de lib, mais le lancement de l'appli démo avec npm start ne permet pas de lancer la v1

**Comment by abdel-djalil** [comment]
Je viens de modifier le main.js pour prendre en compte le lancement de la V1, et j'ai rajouté la documentation.
